name: Frontend CI/CD YML

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14 # You can change the Node.js version if needed

    - name: Install dependencies
      run: npm install

    - name: Build the frontend
      run: npm run build

    - name: Test the application (if applicable)
      run: npm test

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14 # You can change the Node.js version if needed

    - name: Install dependencies
      run: npm install

    - name: Start the frontend application
      run: npm start
